In [553]:
import matplotlib.pyplot as plt
import numpy as np
import random
from matplotlib import animation as anim
from IPython.display import HTML
import matplotlib.patches as mpatches

In [554]:
m = 20
n = 20
step = 100
picture_num = step + 1

In [555]:
def generate(picture_num):
    A = []
    for i in range(picture_num):
        f = open("./output_data/result_p4s100_step" + str(i) + ".txt")
        for line in f:
            line = line.rstrip('\n')
            for word in line:
                num = int(word)
                A.append(num)
    return np.array(A)

In [556]:
def create_animation(A):
    fig = plt.figure(figsize=(12,6))

    plt.title('Game of Life')

    imgs = []
    for i in range(len(A)):
        data = A[i]
        values = np.unique(data.ravel())
        im = plt.imshow(data, interpolation='none', cmap="binary")
        imgs.append([im])
    colors = [ im.cmap(im.norm(value)) for value in values]
    patches = [ mpatches.Patch(color=colors[i], label="Alive" if values[i] else "Dead" ) for i in range(len(values)) ]
    plt.legend(handles=patches, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0. )

    ani = anim.ArtistAnimation(fig, imgs, interval=100, blit=True)
    plt.close(fig)  # prevent final frame plot from showing up inline below

    return ani

In [557]:
A = generate(picture_num)
A = A.reshape(((picture_num, m, n)))
print(A)

[[[1 1 0 ... 1 0 1]
  [1 1 1 ... 1 0 0]
  [0 0 1 ... 1 1 1]
  ...
  [0 1 0 ... 1 1 1]
  [1 0 1 ... 0 0 0]
  [1 0 1 ... 1 1 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 1 0 ... 1 1 1]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [1 0 0 ... 1 1 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[1 0 0 ... 1 1 0]
  [1 0 0 ... 0 1 1]
  [0 0 0 ... 0 1 0]
  ...
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 0 1 0]
  [0 0 0 ... 0 1 1]]

 [[1 0 0 ... 0 0 0]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 1 1 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 1]
  [0 0 0 ... 1 0 0]
  ...
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]]]


In [541]:
ani = create_animation(A)
print('Preparing HTML (takes a little while...)')
HTML(ani.to_jshtml())

Preparing HTML (takes a little while...)
